// Generated by CoffeeScript 1.9.0
var __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  __hasProp = {}.hasOwnProperty;

window.Blackjack = (function(_super) {
  var dealerScore, playerScore;

  __extends(Blackjack, _super);

  function Blackjack() {
    return Blackjack.__super__.constructor.apply(this, arguments);
  }

  dealerScore = [];

  playerScore = [];

  Blackjack.prototype.initialize = function() {
    this.set('deck', new Deck());
    this.set('playerHand', this.get('deck').dealPlayer([this.get('deck').pop(), this.get('deck').pop()]));
    this.set('dealerHand', this.get('deck').dealDealer([this.get('deck').pop().flip(), this.get('deck').pop()]));
    this.checkScores();
    this.get('playerHand').on("add", this.checkScores, this);
    this.get('dealerHand').on("add", this.checkScores, this);
    return this.get('playerHand').on("endTurn", this.dealerTurn, this);
  };

  Blackjack.prototype.dealerTurn = function() {
    if (dealerScore[1] < 17 && dealerScore[0] < 17) {
      this.get('dealerHand').draw();
      return this.dealerTurn();
    } else {
      return this.endGame();
    }
  };

  Blackjack.prototype.endGame = function() {
    if (playerScore[1] > 21) {
      playerScore = playerScore[0];
    } else {
      playerScore = playerScore[1];
    }
    if (dealerScore[1] > 21) {
      dealerScore = dealerScore[0];
    } else {
      dealerScore = dealerScore[1];
    }
    if (playerScore > 21 && dealerScore > 21) {
      return this.tie();
    } else if (playerScore > 21) {
      return this.lose();
    } else if (dealerScore > 21) {
      return this.win();
    } else if (playerScore > dealerScore) {
      return this.win();
    } else if (playerScore === dealerScore) {
      return this.tie();
    } else {
      return this.lose();
    }
  };

  Blackjack.prototype.checkScores = function() {
    playerScore = this.get('playerHand').bjScores();
    dealerScore = this.get('dealerHand').bjScores();
    if (playerScore.indexOf(21) > -1) {
      return this.endGame();
    } else if (playerScore[0] > 21 || dealerScore[0] > 21) {
      return this.endGame();
    }
  };

  Blackjack.prototype.win = function() {
    alert('you win!');
    debugger;
  };

  Blackjack.prototype.tie = function() {
    alert('tie!');
    debugger;
  };

  Blackjack.prototype.lose = function() {
    alert('you lose!');
    debugger;
  };

  return Blackjack;

})(Backbone.Model);
